spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    spring.jpa.show:sql: true

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8